services:
  - type: web
    name: anita-album
    env: node
    buildCommand: npm install && node build.js
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
